# Generated by Django 5.2.1 on 2025-06-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_lostfounditem_latitude_lostfounditem_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfounditem',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='longitude',
        ),
    ]
