# Generated by Django 5.2.1 on 2025-07-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_lostfounditem_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
